name: shop_savvy
description: Flutter & PHP & MYSQL E-commerce Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  lottie: ^2.4.0
  # Firebase And Notification
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  flutter_local_notifications: ^14.1.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  # Local Data Cache
  shared_preferences: ^2.1.2
  # Icon
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.1.4
  responsive_builder: ^0.7.0
  # otp
  flutter_otp_text_field: ^1.1.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  cached_network_image: ^3.2.3
  http: ^0.13.6
  marquee: ^2.2.3





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/lottie/
    - assets/fonts/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - weight: 700

    - family: PlayFairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
        - weight: 700

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
        - weight: 700
