// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50B5DsF-77DQFmXiRUf73rEXggYms_-A',
    appId: '1:36928575052:web:afe2832c329204855706e9',
    messagingSenderId: '36928575052',
    projectId: 'shopsavvy-47a7a',
    authDomain: 'shopsavvy-47a7a.firebaseapp.com',
    storageBucket: 'shopsavvy-47a7a.appspot.com',
    measurementId: 'G-T3G26Z6B3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARhZV95o1x-tFlnACcVoPcINJoWZZardk',
    appId: '1:36928575052:android:a22803bc45c5d7295706e9',
    messagingSenderId: '36928575052',
    projectId: 'shopsavvy-47a7a',
    storageBucket: 'shopsavvy-47a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrIMbHt6hF_cX7FoGTRoo86mpcjK5NQPs',
    appId: '1:36928575052:ios:2c307c66494703815706e9',
    messagingSenderId: '36928575052',
    projectId: 'shopsavvy-47a7a',
    storageBucket: 'shopsavvy-47a7a.appspot.com',
    iosBundleId: 'com.IBMF.ecommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrIMbHt6hF_cX7FoGTRoo86mpcjK5NQPs',
    appId: '1:36928575052:ios:2c307c66494703815706e9',
    messagingSenderId: '36928575052',
    projectId: 'shopsavvy-47a7a',
    storageBucket: 'shopsavvy-47a7a.appspot.com',
    iosBundleId: 'com.IBMF.ecommerceApplication',
  );
}
